### ISSUE TITLE
Is it possible to run cucumber tests as unit tests?

### ISSUE THREAD

**Issue by Enrico2** [bbqsrc/cucumber-rust#60]
The main reason for us for this is that code coverage tools (e.g. [Tarpaulin](https://github.com/xd009642/tarpaulin)) cannot get coverage data from integration tests, only from unit tests. Our cucumber tests are the main source of test cases we have, which we keep adding to (we have the same code implemented in multiple languages, and share .feature files), we'd like to feed those results into code coverage data.

**Comment by bbqsrc** [comment]
If by unit tests you mean with `#[test]`, then unfortunately no. Cucumber is implemented as a completely separate test harness due to limitations of, well, Rust and Cargo, at the moment.

It may be more fruitful to consider how Tarpaulin et al manage coverage testing with Rust tests that are in a `tests` directory and not part of the main codebase, because I suspect, the answer will be the same. This crate simply generates an executable binary just like the basic test harness, so it seems that if Tarpaulin supports examples (it claims it does) then it's not a stretch that they would also support Cucumber.

That said, the next release of this crate will be async-first, so that might introduce more problems for you. Test on the develop branch if you want to see what's coming.

**Comment by Enrico2** [comment]
Thanks, I'm working around the issue atm by writing my own shim in a `#[test]` on top of `gherkin_rust` directly. Our `.feature` files are dead-simple, so fortunately that's feasible.

But long term, I do want to figure out how to generate a coverage report from integration tests.
