### ISSUE TITLE
How to extract steps into spearate files in ./steps directory

### ISSUE THREAD

**Issue by BerhorShadowbuckle** [bbqsrc/cucumber-rust#61]
Hi,
at first big thank you for this library, it's really great!

I'd like to extract steps into separate file(s) in ./steps directory in similar manner how features are (README mentions that it's possible), but I'm not sure how to do that. Could you please show some example (ie. based on code from README) how can I do this?

**Comment by bbqsrc** [comment]
Hey @BerhorShadowbuckle! 

The current released version does make doing that kind of inflexible at the moment. The version on the develop branch is async-aware and replaces the macro with a builder that should make it a bit more obvious how to go about this.

I'll try to make a release of the develop branch plus some documentation over the weekend.

**Comment by ianlet** [comment]
@BerhorShadowbuckle are you trying to achieve something like that?

```
tests
├── cucumber.rs
├── steps
│   ├── my_step.rs
│   └── mod.rs
└── world.rs
```

If so, then the following setup seems to work for me:

```rust
// tests/cucumber.rs

mod world;
mod steps;

use cucumber::{cucumber, before, after};

before!(a_before_fn => |_scenario| {
});

after!(an_after_fn => |_scenario| {
});

fn setup() {
}

cucumber! {
    features: "./features",
    world: crate::world::MyWorld,
    steps: &[
        steps::my_step::steps
    ],
    setup: setup,
    before: &[ a_before_fn ], 
    after: &[ an_after_fn ] 
}
```

```rust
// tests/world.rs

pub struct MyWorld {
    pub foo: String
}

impl cucumber::World for MyWorld {}

impl std::default::Default for MyWorld {
    fn default() -> MyWorld {
        MyWorld { foo: "".to_string() }
    }
}
```

```rust
// tests/steps/mod.rs

pub mod my_step;
```

```rust
// tests/steps/my_step.rs

use cucumber::steps;

steps!(crate::world::MyWorld => {
    given "something" |world, step| {
        // this should work
    };
});
```

**Comment by BerhorShadowbuckle** [comment]
@ianlet Thanks for the hint! I'll check it :)

**Comment by bbqsrc** [comment]
I have now published Cucumber 0.7.0. If you have a look at the example in the readme, you will see for simplicity I have made the steps definition in an inline `mod`. This could very easily be another file that is a module.

Once you have done that, you specify the steps to be used in the cucumber builder. That's it!

**Comment by BerhorShadowbuckle** [comment]
Thanks! :)

**Comment by bbros-dev** [comment]
I would keep this open as a documentation issue.  

The issue of concern is that cucumber-rusts recommendation to place step files inside `test` rather than adopt upstream conventions (java, java-script, ruby, kotkin) of placing steps under `features`.

The reason why `tests` is a poor idea, in my experience, is that it muddles unit tests and executable features.

 Features tend to be written first, then the step definition makes you write a high level function that would make the test green.  This is the end result you need to call to make that Feature step green.  In the course of implementing the function called by the step definition you implement many unit tests - these go in the `tests` folder.

**Comment by rawkode** [comment]
Hmm, should this be re-opened? According to the Rust docs, each file under `tests` is actually compiled as its own crates, meaning that we shouldn't be using `mod <file>` in the `tests` directory.

https://doc.rust-lang.org/book/ch11-03-test-organization.html
