### ISSUE TITLE
"when" step is not found when referred to as a "given" step

### ISSUE THREAD

**Issue by fin-ger** [bbqsrc/cucumber-rust#96]
The Gherkin Reference states

> Keywords are not taken into account when looking for a step definition. This means you cannot have a `Given`, `When`, `Then`, `And` or `But` step with the same text as another step.
> -- https://cucumber.io/docs/gherkin/reference/#steps

I have the following step definition:

```rust
#[when(regex = "a password store is opened (.*)")]
fn a_password_store_is_opened(world: &mut IncrementalWorld, location: String) {
    // ...
}
```

with the following scenarios:

```feature
  Scenario: Open a non-existent password store at the default location
    Given no password store exists
    When a password store is opened at the default location
    Then the opening of the password store fails
```
```feature
  Scenario: Traversing level-order over all entries in the password store
    Given a password store exists at the default location
    And a password store is opened at the default location
    And the password store is successfully opened
    When the password store is traversed in level-order
    Then the passwords and directories are iterated in level-order form
```

However, the second scenario leads to the following output:
![image](https://user-images.githubusercontent.com/5300274/101536974-0d40d980-399b-11eb-8d63-58d235dfa434.png)

When switching `And` to `When` the scenario succeed.

However, I think this conflicts with the above mentioned statement from the Gherkin Reference documentation. In my interpretation, it should make no difference whether a step is defined as `given`, `when`, or `then`.

Am I interpreting the documentation wrong?

**Comment by bbqsrc** [comment]
You are interpreting the reference correctly, I think. The implementation in Rust does not follow that logic it seems. (I write it seems even though I wrote the parser, heh).

I do wonder whether or not this is a misfeature of the specification or a bug in our implementation. I have my suspicions that the answer lies in-between. `Given` is meant to be used for setting up context, while `when` is a check condition. Using the same step for both strikes me as an error, unless the dev actively opts into it.

Would a model where it errors with a useful error message asking the dev to opt-in be a useful solution here?

**Comment by fin-ger** [comment]
Hmm, in the first scenario I check whether a password store can be successfully opened and in the second I use the same code to ensure a password store is successfully opened. I can duplicate the code, but I think this would be unnecessary as all the steps should always have a unique name. Therefore I would have to come up with another "name" for the "given" step although it does exactly the same thing: it opens a password store at the default location.

However, this is the first time I'm using Cucumber and don't know how other implementations handle this.

An intuitive approach (for me) however would be to completely ignore the keywords and just use the step name as the reference clearly states that every step must have a unique name.

**Comment by fin-ger** [comment]
I'm sorry, I did not answer the question: I think an error for this behavior with an opt-in would be a solution for me. However, I still think this would not conform with the Gherkin Reference as a step is identified by it's name.

**Comment by jarrrgh** [comment]
I've been missing this too. I've only used Ruby implementation earlier and I'm pretty sure the keywords were interchangeable.

**Comment by bbqsrc** [comment]
I've been thinking about this more today. I'd say a few things:

- Cucumber/Gherkin spec is non-normative and inconsistently applied amongst the official implementations, so following it coherently is potentially more expensive than any value it is to provide
- This is a Cucumber implementation for Rust, not any other language. Rust is a language of explicitness and types. Stringly typing things is we end up with nothing but great pain.

I am most familiar with the officlal Node.js implementation of Cucumber. In their [example](https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md), you can see each of the steps are declared with the relevant keyword as a function call.

So, my interpretation of the step definition quoted:

> Keywords are not taken into account when looking for a step definition.

This is not true even for the official implementations. In Rust, we check if the feature uses Given, When or Then, and if And or But is used, it uses the previous keyword seen in that scenario. I suspect that this statement in and of itself is spurious and unnecessary, as the very next sentence cancels it out.

> This means you cannot have a Given, When, Then, And or But step with the same text as another step.

This explicitly rules out reusing the same step for multiple keywords. Something like `Given foo` and `When foo` is a logic error and should not work.

In effect, if you are trying to reuse the same step text in a Given and When step, you are likely mixing up the purpose of that step. Given should set up the context for your test, and When should be actions taken. I understand that these two can be ambiguous, but in effect, a given is something that should just be there, and a when is an action a user (or other actor) would take upon those given things to cause a behaviour effect tested in a then. :smile:

@fin-ger the solution to your problem is just change the When to a Given.

**Comment by fin-ger** [comment]
Alright, this sounds reasonable to me. I changed my scenarios to

```feature
  Scenario: Open a non-existent password store at the default location
    Given no password store exists
    And a password store is opened at the default location
    Then the opening of the password store fails
```

I might have been mislead by the impression that a `Given` step cannot lead to a `Then` step directly, but as I am testing my setup, I guess this is the clean approach.

Thanks for all your feedback!

For me the issue is solved and you are free to close it!

**Comment by bbqsrc** [comment]
@fin-ger you can even have `Given`s _later_ in a test. There's no enforced ordering for them :smile:

You're welcome. If you have any other troubles, feel free to open another issue. :smile:

**Comment by ilslv** [comment]
@fin-ger 
> I can duplicate the code, but I think this would be unnecessary as all the steps should always have a unique name.

You can add multiple attributes to a single function. Also I'm planning to add `#[step(...)]` attribute, which will match `Given`, `When` and `Then` steps.
```rust
#[when(regex = "a password store is opened (.*)")]
#[given(regex = "a password store is opened (.*)")]
fn a_password_store_is_opened(world: &mut IncrementalWorld, location: String) {
    // ...
}
```

If you have some step-specific logic, you can add `step` argument and match on it's type
```rust
#[when(regex = "a password store is opened (.*)")]
#[given(regex = "a password store is opened (.*)")]
fn a_password_store_is_opened(world: &mut IncrementalWorld, location: String, step: &Step) {
    // ...
    match step.ty {
        StepType::Given => { ... },
        StepType::When=> { ... },
        StepType::Then=> unreachable!(),
    }
}
```

**Comment by Shamaoke** [comment]
> Also I'm planning to add #[step(...)] attribute, which will match Given, When and Then steps.

@ilslv Is there any progress on this?
